"""empty message

Revision ID: 4a5405044b3f
Revises: 44d41fa37f7c
Create Date: 2021-10-25 13:46:55.220199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5405044b3f'
down_revision = '44d41fa37f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlyCPI',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cpi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlyCPI')
    # ### end Alembic commands ###
