"""empty message

Revision ID: 5cb0213e9a2b
Revises: 4a5405044b3f
Create Date: 2021-10-25 17:15:01.739491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb0213e9a2b'
down_revision = '4a5405044b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyEOD',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('monthlyCPI',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cpi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlyCPI')
    op.drop_table('dailyEOD')
    # ### end Alembic commands ###
